version: "3"
env:
  TEST_TIMEOUT:
    sh: echo ${TEST_TIMEOUT:-"5m"}

tasks:
  run-tests:
    desc: "Run tests"
    cmds:
      - |
        mkdir -p coverage
        go test -failfast -timeout $TEST_TIMEOUT -race -cover -coverprofile=coverage/structviewer.cov -v ./...
