version: "3"
env:
  TEST_TIMEOUT:
    sh: echo ${TEST_TIMEOUT:-"5m"}

tasks:
  run-tests:
    desc: "Run tests"
    cmds:
      - |
        go test -failfast -timeout $TEST_TIMEOUT -race -cover -coverprofile=structviewer.cov -v ./...
        mkdir -p "coverage"
        mv *.cov "coverage/"

  merge-coverage:
    desc: "Merge coverage files into a single file"
    cmds:
      - |
        gocovmerge $(find . -name '*.cov') > merged-coverage.cov
